conda-forge/sagelib-feedstock

recipe/activate/activate.sh, recipe/activate/deactivate.sh, recipe/build.sh, recipe/meta.yaml, recipe/patches/disable-sage-location.patch
@saraedum, I've implemented most of the changes you mentioned here. Let me know if you'd like to be added as a maintainer here.
=> Build sagelib using setup.py

recipe/build.sh
See https://conda.io/docs/building/environment-vars.html#environment-variables-set-during-the-build-process
=> Use more than two CPUs

recipe/meta.yaml
and check that Sage actually starts (as we claim in the comment)
=> Document how we choose the runtime dependencies

recipe/meta.yaml
since Sage builds against it, see also https://github.com/conda-forge/sagelib-feedstock/pull/22#pullrequestreview-124226252
=> Add givaro and fflas-ffpack as dependencies

.ci_support/linux_python2.7.yaml, .ci_support/osx_python2.7.yaml, recipe/meta.yaml
that's what conda-forge-pinning is set to (and e.g. giac uses.)
=> Downgrade gsl to 2.2

recipe/meta.yaml
=> Downgrade arb, pynac and numpy

.ci_support/linux_python2.7.yaml, .ci_support/linux_python3.6.yaml, .ci_support/osx_python2.7.yaml, .ci_support/osx_python3.6.yaml, recipe/meta.yaml, recipe/patches/cddlib-094j.patch
so we can use a version of cddlib that also works for gfan
=> Backport https://trac.sagemath.org/ticket/25344

recipe/meta.yaml, recipe/patches/25260.patch, recipe/patches/series
=> Upgrade to NumPy 1.15.2

recipe/meta.yaml, recipe/patches/25345.patch, recipe/patches/series
this does not really change anything but just adapt some doctests so we effectively skip them.
=> Backport 25345 to make more tests pass

recipe/meta.yaml, recipe/patches/25786.patch, recipe/patches/series
there has been no movement on that ticket but I think it's ready, so we should backport it.
Fixes #39.
=> Backport #25786

recipe/meta.yaml, recipe/patches/26434.patch, recipe/patches/series
to fix threejs viewer in jupyter
=> Backport #26434

recipe/meta.yaml, recipe/patches/26451.patch, recipe/patches/series
to support newer versions of Sphinx
=> Backport #26451

recipe/meta.yaml, recipe/patches/25806.patch, recipe/patches/26451.patch, recipe/patches/series
to fix timeouts when invoking R
=> Backport #25806

recipe/build.sh, recipe/meta.yaml
=> remove lib64 symlink

recipe/build.sh, recipe/meta.yaml
=> Use singular 4.1.1

recipe/activate/activate.sh, recipe/build.sh, recipe/meta.yaml, recipe/patches/25786.patch
=> Fix introspection by copying some files in SAGE_DOC_SRC

recipe/meta.yaml
=> Remove matplotlib and pkgconfig from run

recipe/meta.yaml
=> Bump to 8.9.rc0

recipe/build.sh, recipe/meta.yaml
=> Fix sage-env

recipe/build.sh, recipe/meta.yaml
=> Multiarch fix

recipe/meta.yaml
=> Update to 8.9.rc1

recipe/build.sh, recipe/meta.yaml
=> Use pip to install sage_conf

recipe/build.sh, recipe/meta.yaml
=> install sage_docbuild

recipe/build.sh, recipe/meta.yaml
Checklist
Fixes https://github.com/conda-forge/sage-feedstock/issues/72
=> Add symlink for threejs_sage

recipe/meta.yaml
=> remove pynac

.azure-pipelines/azure-pipelines-osx.yml, .circleci/config.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, LICENSE.txt, build-locally.py, recipe/build.sh, recipe/meta.yaml
Checklist
@conda-forge-admin, rerender
=> Use threejs-sage

README.md, recipe/build.sh, recipe/install-bliss-ext.sh, recipe/install-sirocco-ext.sh, recipe/meta.yaml, recipe/optional-ext.diff
Closes https://github.com/conda-forge/sagelib-feedstock/pull/139
=> Package sagemath-sirocco and sagemath-bliss

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.21python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.21python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml, .ci_support/linux_aarch64_numpy1.21python3.8.____cpython.yaml, .ci_support/linux_aarch64_numpy1.21python3.9.____cpython.yaml, .ci_support/linux_aarch64_numpy1.23python3.11.____cpython.yaml, .ci_support/migrations/python311.yaml, .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.8.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.21python3.8.____cpython.yaml, .ci_support/osx_arm64_numpy1.21python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, README.md, recipe/build.sh, recipe/meta.yaml
=> python 3.11 support

recipe/build.sh, recipe/meta.yaml
Checklist
Fixes https://github.com/conda-forge/sage-feedstock/issues/91
=> Fix osx-arm64

recipe/meta.yaml
some of these pins contradict what sage-feedstock does, some are just not needed anymore.
Checklist
=> Cleanup outdated pins

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_numpy1.26python3.12.____cpython.yaml, .ci_support/linux_aarch64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_aarch64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_aarch64_numpy1.23python3.11.____cpython.yaml, .ci_support/linux_aarch64_numpy1.26python3.12.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.26python3.12.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml, .gitignore, recipe/build-env.sh, recipe/meta.yaml
=> remove clang-14 workaround
